site_name: python-pptx-snippets
nav:
  - Home: index.md
theme:
  name: material 
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_symbol_type_heading: true
            show_category_heading: true
            parameter_headings: true
